/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.sfsu.evaluator.view.menu.add;

import edu.sfsu.evaluator.EvaluatorController;
import edu.sfsu.evaluator.EvaluatorViewModel;
import edu.sfsu.util.io.InputValidator;
import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 * Dialog for adding new entity types.
 * @author eric
 */
public class AddEntityTypeDialog extends javax.swing.JDialog
{

    private EvaluatorViewModel viewModel;
    private EvaluatorController controller;


    /**
     * Creates new form AddEntityTypeDialog
     */
    public AddEntityTypeDialog(EvaluatorViewModel viewModel,
                                   EvaluatorController controller)
    {
        super(controller.getEvaluatorFrame(), true);
        initComponents();
        this.viewModel = viewModel;
        this.controller = controller;
        // Set initial color to a random color.
        Random rand = new Random();
        float r = rand.nextFloat();
        float g = rand.nextFloat();
        float b = rand.nextFloat();
        Color randomColor = new Color(r, g, b);
        colorChooser.setColor(randomColor);
    }

    // Display this dialog
    public static void showAddEntityTypeDialog(
            EvaluatorViewModel viewModel, EvaluatorController controller)
    {
        AddEntityTypeDialog aDialog =
                new AddEntityTypeDialog(viewModel, controller);
        aDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        colorChooser = new javax.swing.JColorChooser();
        entityTypeNameTextField = new javax.swing.JTextField();
        infoLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Annotation Type");

        infoLabel.setText("Entity Type Name");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entityTypeNameTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(entityTypeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_createButtonActionPerformed
    {//GEN-HEADEREND:event_createButtonActionPerformed
        // Get user entity type name from
        String newEntityTypeName = entityTypeNameTextField.getText();
        // Validate user input
        if (newEntityTypeName == null)
        {
            String message = "Invalid entity type";
            JOptionPane.showMessageDialog(this, message,
                                          "Naming Error",
                                          JOptionPane.ERROR_MESSAGE);
        } else if (!InputValidator.isValidUserInput(newEntityTypeName))
        {
            String message =
                    String.format("Invalid entitytype '%s'", newEntityTypeName);
            JOptionPane.showMessageDialog(this, message,
                                          "Naming Error",
                                          JOptionPane.ERROR_MESSAGE);
        } else if (viewModel.getEntityTypes().containsKey(newEntityTypeName))
        {
            String message =
                    String.format("Already existing entity type '%s'",
                                  newEntityTypeName);
            JOptionPane.showMessageDialog(this, message,
                                          "Naming Error",
                                          JOptionPane.ERROR_MESSAGE);
        } else
        {
            // If new entity type name checks out, add new entity type
            Color color = colorChooser.getColor();
            if (color == null)
            {
                color = Color.BLACK;
            }
            controller.requestEntityTypeAdd(newEntityTypeName, color);
            viewModel.repaintView();
            dispose();
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField entityTypeNameTextField;
    private javax.swing.JLabel infoLabel;
    // End of variables declaration//GEN-END:variables
}
